[package]
edition = "2021"
name = "imessage-exporter"
version = "0.0.0"

[dependencies]
clap = "3.1.18"
imessage-database = {path = "../imessage-database"}
rusqlite = {version = "0.26.3", features = ["blob"]}
