[package]
edition = "2021"
name = "imessage-exporter"
version = "0.0.0"

[dependencies]
clap = {version = "3.2.22", features = ["cargo"]}
imessage-database = {path = "../imessage-database"}
indicatif = "0.17.1"
rusqlite = {version = "0.28.0", features = ["blob"]}
uuid = {version = "1.1.2", features = ["v4", "fast-rng"]}
