[package]
edition = "2021"
name = "imessage-database"
version = "0.0.0"
description = "Parsers and tools to interact with iMessage data"
license = "GPL 3.0"

[dependencies]
chrono = "0.4.23"
plist = "1.3.1"
rusqlite = {version = "0.28.0", features = ["blob"]}
